#!/usr/bin/env node
/**
 * ad_editor_server.js — Creative GUI Editor バックエンド
 * localhost:3002 で起動。creative_editor.html を配信しAPIを提供。
 */
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PORT = 3002;
const SCENES_FILE = path.join(__dirname, '../knowledge/creative_dataset/lp_ad_scenes.json');
const PUBLIC_DIR  = path.join(__dirname, '../../media/remotion/public');
const TSX_FILE    = path.join(__dirname, '../../media/remotion/src/templates/lp/LpAd.tsx');
const EDITOR_HTML = path.join(__dirname, 'creative_editor.html');

// ── CORS helper ────────────────────────────────────
function setCORS(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

// ── JSON body reader ───────────────────────────────
function readBody(req) {
  return new Promise((resolve) => {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try { resolve(JSON.parse(body)); }
      catch { resolve({}); }
    });
  });
}

// ── TSX codegen from scenes.json ───────────────────
function regenTSX(scenes) {
  const fps = 30;
  const sceneList = scenes.formats['30s'].scenes;

  // SCENE定数
  const sceneConst = sceneList.map(s =>
    `  ${s.id.replace('-', '_')}:   { dur: ${Math.round(s.duration_s * fps)}, label: '${s.label || s.id}' },`
  ).join('\n');

  // from計算
  let cumulative = 0;
  const fromConst = sceneList.map(s => {
    const line = `  ${s.id.replace('-', '_')}:   ${cumulative},`;
    cumulative += Math.round(s.duration_s * fps);
    return line;
  }).join('\n');

  const total = cumulative;

  // タイムライン定義をJSONとして埋め込み
  const scenesJSON = JSON.stringify(sceneList, null, 2)
    .split('\n').map(l => '// ' + l).join('\n');

  const tsx = `import {
  AbsoluteFill, useCurrentFrame, interpolate, spring,
  useVideoConfig, Sequence, Audio, staticFile,
} from 'remotion';
import React from 'react';
import { loadFont } from '@remotion/google-fonts/NotoSansJP';

// AUTO-GENERATED by ad_editor_server.js — DO NOT EDIT DIRECTLY
// Edit via GUI: http://localhost:3002
// Source of truth: lp_ad_scenes.json
//
${scenesJSON}

const { fontFamily } = loadFont('normal', { weights: ['400', '700', '900'] });

const SCENE = {
${sceneConst}
};
const from = {
${fromConst}
};
const TOTAL = ${total};

// Design tokens
const BG_DARK    = '#080810';
const BG_MID     = '#0F0F1A';
const PURE_WHITE = '#FFFFFF';
const SILVER     = '#A8A8B8';
const GOLD       = '#C8A96A';
const ACCENT_RED = '#E03030';
const FONT       = fontFamily;

const AnimatedBG: React.FC<{ frame: number; color1?: string; color2?: string; opacity?: number }> = ({
  frame, color1 = '#0B0B2A', color2 = '#05050F', opacity = 1,
}) => {
  const shift = interpolate(frame, [0, 300], [0, 30], { extrapolateRight: 'clamp' });
  return (
    <div style={{
      position: 'absolute', inset: 0, opacity,
      background: \`radial-gradient(ellipse at \${50 + shift * 0.3}% \${40 + shift * 0.1}%, \${color1} 0%, \${color2} 70%)\`,
    }} />
  );
};

const KineticLines: React.FC<{ frame: number; count?: number; opacity?: number }> = ({
  frame, count = 5, opacity = 0.06,
}) => (
  <div style={{ position: 'absolute', inset: 0, overflow: 'hidden', opacity }}>
    {Array.from({ length: count }).map((_, i) => {
      const y = 15 + i * 18;
      const x = ((frame * (0.4 + i * 0.15)) % 130) - 10;
      return (
        <div key={i} style={{
          position: 'absolute', top: \`\${y}%\`, left: \`\${x}%\`,
          width: '60%', height: 1,
          background: \`linear-gradient(90deg, transparent, \${PURE_WHITE}, transparent)\`,
          transform: \`rotate(\${-8 + i * 3}deg)\`,
        }} />
      );
    })}
  </div>
);

${sceneList.map(s => generateSceneComponent(s)).join('\n\n')}

export const LpAd: React.FC = () => {
  const { fps } = useVideoConfig();
  return (
    <AbsoluteFill style={{ backgroundColor: BG_DARK, fontFamily: FONT }}>
      <Audio src={staticFile('bgm_ad.mp3')} startFrom={0} volume={0.18} />
${sceneList.map(s => {
  const id = s.id.replace('-', '_');
  return `      <Sequence from={from.${id}} durationInFrames={SCENE.${id}.dur}>
        <Audio src={staticFile('${s.narration_file || 'lp_'+s.id+'.mp3'}')} startFrom={0} volume={1} />
        <Scene_${capitalize(s.id)} fps={fps} />
      </Sequence>`;
}).join('\n')}
    </AbsoluteFill>
  );
};

export const LP_AD_TOTAL_FRAMES = TOTAL;
`;
  return tsx;
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function generateSceneComponent(s) {
  const name = `Scene_${capitalize(s.id)}`;
  const emotion = s.emotion || 'neutral';
  const color = {
    empathy: "'#0A0A25', '#06060F'",
    fomo: "'#150A0A', '#070305'",
    fomo_peak: "'#1A0808', '#090303'",
    hope: "'#0A1520', '#050A10'",
    liberation: "'#0A1020', '#050810'",
  }[emotion] || "'#0B0B2A', '#05050F'";

  return `const ${name}: React.FC<{ fps: number }> = ({ fps }) => {
  const frame = useCurrentFrame();
  const dur = SCENE.${s.id.replace('-', '_')}.dur;
  const opacity = interpolate(frame, [0, 20, dur - 15, dur], [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
  const scale = spring({ frame, fps, from: 0.92, to: 1, config: { damping: 16, stiffness: 70 } });
  return (
    <AbsoluteFill style={{ opacity }}>
      <AnimatedBG frame={frame} color1={${color.split(',')[0]}} color2={${color.split(',')[1]}} />
      <KineticLines frame={frame} count={5} opacity={0.05} />
      <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center' }}>
        <div style={{ textAlign: 'center', paddingInline: 72, transform: \`scale(\${scale})\` }}>
          <h2 style={{
            color: PURE_WHITE, fontSize: 72, fontWeight: 900,
            lineHeight: 1.4, letterSpacing: '-0.02em', margin: 0,
          }}>
            {/* Scene: ${s.label || s.id} (${s.emotion}) */}
          </h2>
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};`;
}

// ── HTTP Server ────────────────────────────────────
const server = http.createServer(async (req, res) => {
  setCORS(res);
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  const url = new URL(req.url, `http://localhost:${PORT}`);
  const pat = url.pathname;

  // ─ GET /api/scenes
  if (pat === '/api/scenes' && req.method === 'GET') {
    const data = fs.readFileSync(SCENES_FILE, 'utf8');
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(data);
    return;
  }

  // ─ POST /api/scenes  (save + regen)
  if (pat === '/api/scenes' && req.method === 'POST') {
    const body = await readBody(req);
    fs.writeFileSync(SCENES_FILE, JSON.stringify(body, null, 2));

    // LpAd.tsxは現状の実装を保持（コードジェネレーションは将来拡張）
    // 現状はJSONのみ更新してRemotionStudioのホットリロードに任せる
    const result = { ok: true, message: 'scenes.json saved', totalFrames: body.formats?.['30s']?.total_frames };
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    console.log(`[SAVE] scenes.json updated (${JSON.stringify(body.formats?.['30s']?.scenes?.length)} scenes)`);
    return;
  }

  // ─ GET /api/assets  (mp3 list)
  if (pat === '/api/assets' && req.method === 'GET') {
    try {
      const files = fs.readdirSync(PUBLIC_DIR)
        .filter(f => /\.(mp3|mp4|wav|ogg|webm)$/.test(f))
        .map(f => ({ name: f, size: fs.statSync(path.join(PUBLIC_DIR, f)).size }));
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(files));
    } catch {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end('[]');
    }
    return;
  }

  // ─ GET /api/tsx  (LpAd.tsx current content)
  if (pat === '/api/tsx' && req.method === 'GET') {
    const content = fs.existsSync(TSX_FILE) ? fs.readFileSync(TSX_FILE, 'utf8') : '';
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end(content);
    return;
  }

  // ─ POST /api/tsx  (direct TSX save)
  if (pat === '/api/tsx' && req.method === 'POST') {
    const body = await readBody(req);
    if (body.content) {
      fs.writeFileSync(TSX_FILE, body.content);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ ok: true }));
      console.log(`[SAVE] LpAd.tsx updated (${body.content.length} chars)`);
    } else {
      res.writeHead(400); res.end('{}');
    }
    return;
  }

  // ─ Static: creative_editor.html
  if (pat === '/' || pat === '/index.html') {
    if (fs.existsSync(EDITOR_HTML)) {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(fs.readFileSync(EDITOR_HTML));
    } else {
      res.writeHead(404); res.end('creative_editor.html not found');
    }
    return;
  }

  res.writeHead(404); res.end('Not found');
});

server.listen(PORT, () => {
  console.log(`\n🎬 Creative Editor Server running`);
  console.log(`   GUI:    http://localhost:${PORT}`);
  console.log(`   API:    http://localhost:${PORT}/api/scenes`);
  console.log(`   Assets: http://localhost:${PORT}/api/assets`);
  console.log(`\n📂 Watching: ${path.basename(SCENES_FILE)}`);
  console.log('   Edit in GUI → POST /api/scenes → JSON保存\n');
});
