const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

/**
 * Skill Hunter (Chaos Edition)
 * 
 * Usage: node skill_hunter.js <topic>
 */

const topic = process.argv[2];
if (!topic) {
  console.error("Usage: node skill_hunter.js <topic>");
  process.exit(1);
}

console.log(`🔍 Hunting for skill: ${topic}...`);

// Create a template file for the agent to fill
const templateContent = `# Skill: ${topic}
<!-- 
INSTRUCTION TO AGENT:
1. Use 'search_web' to find:
   - "Best practices for ${topic}"
   - "Common pitfalls in ${topic}"
   - "Minimal working example code for ${topic}"
2. Replace the placeholders below with your findings.
3. Delete these comments.
-->

## Core Concepts
(Summarize what this is in 1-2 sentences)

## Best Practices
- (Example: Prefer X over Y because...)
- (Example: Configuration settings for performance...)

## Common Pitfalls
- (Example: Typical error Z occurs when...)

## Observed Anti-Patterns (Chaos Results)
<!-- 
Fill this section AFTER running chaos_monkey.js.
Record what inputs caused failures and how to prevent them.
-->
- [ ] Input: ... -> Result: ... -> Fix: ...

## Minimal Working Example
\`\`\`
// Provide a copy-paste ready code snippet here
\`\`\`

Generated by Skill Hunter on ${new Date().toISOString()}
`;

const outputPath = path.join(__dirname, '..', '..', 'temp_skills', `${topic.replace(/\s+/g, '_').toLowerCase()}.md`);

// Ensure directory exists
const dir = path.dirname(outputPath);
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

if (!fs.existsSync(outputPath)) {
    fs.writeFileSync(outputPath, templateContent);
    console.log(`✅ Skill template created at: ${outputPath}`);
} else {
    console.log(`ℹ️ Skill file already exists at: ${outputPath}`);
}

console.log(`
---------------------------------------------------
🤖 AGENT ACTION REQUIRED:
1. Open the file: ${outputPath}
2. Run 'search_web' for "${topic}"
3. Fill in the template with high-quality information.
---------------------------------------------------
`);
